<?php
// Dynamic PWA manifest (package Y, customer branding): name, colors and icons
// come from the CMS (data/app-config.json -> branding + uploaded icons in
// data/uploads/pwa-icon-*.png). The app swaps the manifest link at runtime to
// this file once branding.manifest is set; without a PHP backend the static
// manifest.webmanifest from the build continues to apply.

declare(strict_types=1);

require_once __DIR__ . '/db.php'; // push_config() → dataDir

$dataDir = rtrim((string) (push_config()['dataDir'] ?? (__DIR__ . '/../data')), "/\\");

/** Read a JSON file from data/ (or []). */
$readJson = static function (string $file) use ($dataDir): array {
    $path = "$dataDir/$file";
    if (!is_file($path)) {
        return [];
    }
    $data = json_decode((string) file_get_contents($path), true);
    return is_array($data) ? $data : [];
};

$cfg      = $readJson('app-config.json');
$branding = is_array($cfg['branding'] ?? null) ? $cfg['branding'] : [];
$festival = $readJson('app-festival.json') ?: $readJson('festival.json');

$isHex = static fn($v): bool => is_string($v) && preg_match('/^#[0-9a-fA-F]{6}$/', $v) === 1;

$name  = trim((string) ($branding['title'] ?? '')) ?: trim((string) ($festival['name'] ?? '')) ?: 'Festivadget';
$short = trim((string) ($branding['shortName'] ?? '')) ?: trim((string) ($festival['shortName'] ?? ''))
    ?: (function_exists('mb_substr') ? mb_substr($name, 0, 12) : substr($name, 0, 12));

$darkBg = $branding['colors']['dark']['bg'] ?? null;
$accent = $branding['colors']['accent'] ?? null;
$themeColor      = $isHex($darkBg) ? $darkBg : '#121212';
$backgroundColor = $themeColor;

// Prefer custom icons (generated by the CMS), otherwise the build icons.
$uploads = "$dataDir/uploads";
$v       = (string) ($branding['icons'] ?? '');
$icons   = [];
if ($v !== '' && is_file("$uploads/pwa-icon-192.png") && is_file("$uploads/pwa-icon-512.png")) {
    $icons[] = ['src' => "/data/uploads/pwa-icon-192.png?v=$v", 'sizes' => '192x192', 'type' => 'image/png'];
    $icons[] = ['src' => "/data/uploads/pwa-icon-512.png?v=$v", 'sizes' => '512x512', 'type' => 'image/png'];
    if (is_file("$uploads/pwa-icon-maskable.png")) {
        $icons[] = [
            'src'     => "/data/uploads/pwa-icon-maskable.png?v=$v",
            'sizes'   => '512x512',
            'type'    => 'image/png',
            'purpose' => 'maskable',
        ];
    }
} else {
    $icons[] = ['src' => '/icons/icon-192.png', 'sizes' => '192x192', 'type' => 'image/png'];
    $icons[] = ['src' => '/icons/icon-512.png', 'sizes' => '512x512', 'type' => 'image/png'];
    $icons[] = ['src' => '/icons/icon-maskable-512.png', 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'maskable'];
}

$manifest = [
    'name'             => $name,
    'short_name'       => $short,
    'description'      => 'Festival-Begleiter für mehrtägige Events – offline-fähig.',
    'lang'             => 'de',
    'theme_color'      => $themeColor,
    'background_color' => $backgroundColor,
    'display'          => 'standalone',
    'orientation'      => 'portrait',
    'start_url'        => '/',
    'scope'            => '/',
    'icons'            => $icons,
];

header('Content-Type: application/manifest+json; charset=utf-8');
header('Cache-Control: no-cache'); // Branding-Änderungen sollen sofort greifen
echo json_encode($manifest, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
